import uuid
from datetime import datetime

from sqlalchemy import DateTime, Float, ForeignKey, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class Report(Base):
    __tablename__ = "reports"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("interview_sessions.id"), unique=True, nullable=False)

    # ── Scalar summary fields (kept for dashboard queries) ────────────────
    overall_score: Mapped[float] = mapped_column(Float, nullable=False)
    technical_score: Mapped[float] = mapped_column(Float, nullable=False)
    behavioral_score: Mapped[float] = mapped_column(Float, nullable=False)
    communication_score: Mapped[float] = mapped_column(Float, nullable=False)

    strengths: Mapped[dict] = mapped_column(JSONB, nullable=False, default=list)
    weaknesses: Mapped[dict] = mapped_column(JSONB, nullable=False, default=list)
    hiring_recommendation: Mapped[str] = mapped_column(nullable=False)
    learning_plan: Mapped[dict] = mapped_column(JSONB, nullable=False, default=list)
    summary: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # ── Full rich report (all 13 sections as a single JSONB blob) ─────────
    # Null for reports generated by the old agent; populated for new ones.
    full_report: Mapped[dict | None] = mapped_column(JSONB, nullable=True, default=None)

    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    session = relationship("InterviewSession", back_populates="report")

