"""add mcq_data to questions

Revision ID: 554ee10ed156
Revises: 40eca968cc29
Create Date: 2026-08-07 03:34:44.705384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '554ee10ed156'
down_revision = '40eca968cc29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_sessions', 'company_intel',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('questions', sa.Column('mcq_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'mcq_data')
    op.alter_column('interview_sessions', 'company_intel',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###
