"""Add proctoring metrics

Revision ID: 695edeee38f6
Revises: 72132ba550f7
Create Date: 2026-08-26 07:24:05.071955

"""
from alembic import op
import sqlalchemy as sa


revision = '695edeee38f6'
down_revision = '72132ba550f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('look_away_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('interview_sessions', sa.Column('head_turned_duration_seconds', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('interview_sessions', sa.Column('face_not_detected_duration_seconds', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('interview_sessions', sa.Column('multiple_faces_detected_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'multiple_faces_detected_count')
    op.drop_column('interview_sessions', 'face_not_detected_duration_seconds')
    op.drop_column('interview_sessions', 'head_turned_duration_seconds')
    op.drop_column('interview_sessions', 'look_away_count')
    # ### end Alembic commands ###
