"""Add tab_switches to InterviewSession

Revision ID: 72132ba550f7
Revises: 554ee10ed156
Create Date: 2026-08-25 04:03:29.510119

"""
from alembic import op
import sqlalchemy as sa


revision = '72132ba550f7'
down_revision = '554ee10ed156'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('tab_switches', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'tab_switches')
    # ### end Alembic commands ###
