"""add_full_report_to_reports

Revision ID: 91813091ced5
Revises: ece605ba25f2
Create Date: 2026-08-06 04:59:01.793054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '91813091ced5'
down_revision = 'ece605ba25f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('full_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('reports', 'summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('reports', 'full_report')
    # ### end Alembic commands ###
