"""add termination fields to interview_sessions

Revision ID: c6826a26bd25
Revises: 695edeee38f6
Create Date: 2026-08-27 00:28:43.078217

"""
from alembic import op
import sqlalchemy as sa


revision = 'c6826a26bd25'
down_revision = '695edeee38f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('termination_reason', sa.String(length=255), nullable=True))
    op.add_column('interview_sessions', sa.Column('termination_violation_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'termination_violation_count')
    op.drop_column('interview_sessions', 'termination_reason')
    # ### end Alembic commands ###
