"""
Report API schemas.

ReportResponse exposes both:
  - The existing scalar fields (overall_score, strengths, etc.) for
    backward compatibility.
  - The full_report JSONB blob with all 13 rich sections.
"""
from __future__ import annotations

from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import BaseModel


# ---------------------------------------------------------------------------
# Rich report sub-models (used by the frontend for structured access)
# ---------------------------------------------------------------------------

class ScoreCategory(BaseModel):
    category: str
    score: float
    max_score: float = 100
    explanation: str = ""


class StrengthInsight(BaseModel):
    strength: str
    confidence: int = 0
    evidence: str = ""
    related_questions: list[str] = []


class WeaknessInsight(BaseModel):
    topic: str
    severity: str = "MEDIUM"  # HIGH | MEDIUM | LOW
    current_level: str = ""
    evidence: str = ""
    why_it_matters: str = ""
    how_to_improve: str = ""


class ImprovementInsight(BaseModel):
    focus: str = ""
    why: str = ""
    estimated_score_impact: str = ""
    next_action: str = ""


class QuestionAnalysis(BaseModel):
    question_number: int
    stage: str = ""
    question: str
    candidate_answer: str = ""
    score: float
    relevance_classification: str = ""
    what_you_did_well: str = ""
    what_was_missing: str = ""
    why_points_were_lost: str = ""
    how_to_improve: str = ""


class AnswerPattern(BaseModel):
    primary_style: str = ""
    positive_effect: str = ""
    risk: str = ""
    recommendation: str = ""


class QuestionScore(BaseModel):
    question_number: int
    question_short: str = ""
    score: float
    stage: str = ""
    is_followup: bool = False


class DailyImprovementPlan(BaseModel):
    day: int
    topic: str
    goal: str = ""
    practice_task: str = ""
    expected_outcome: str = ""


class RadarAxis(BaseModel):
    axis: str
    score: float


class GitHubProjectInsights(BaseModel):
    verified_claims: list[str] = []
    partial_claims: list[str] = []
    claims_needing_explanation: list[str] = []
    likely_interview_topics: list[str] = []
    credibility_score: int | None = None
    summary: str = ""


class PerformanceInsights(BaseModel):
    overall_pattern: str = ""
    strongest_pattern: str = ""
    weakest_pattern: str = ""
    follow_up_performance: str = ""
    answer_style: str = ""
    trend: str = "stable"  # improving | declining | stable | mixed


# ---------------------------------------------------------------------------
# Main response model
# ---------------------------------------------------------------------------

class ReportResponse(BaseModel):
    # ── Identity ──────────────────────────────────────────────────────────
    id: str
    session_id: str
    created_at: datetime

    # ── Top-level scalars ─────────────────────────────────────────────────
    overall_score: float
    performance_level: str = ""
    executive_summary: str = ""

    readiness_score: float = 0
    readiness_level: str = ""
    readiness_explanation: str = ""

    technical_score: float
    behavioral_score: float
    communication_score: float
    hiring_recommendation: str
    summary: str

    # ── Backward-compat flat lists ────────────────────────────────────────
    strengths_flat: list[str] = []   # flat strings extracted from strengths
    weaknesses_flat: list[str] = []  # flat strings extracted from weaknesses
    learning_plan: list[str] = []    # flat strings extracted from 7-day plan

    # ── Rich structured sections (null when generated by old agent) ───────
    performance_insights: PerformanceInsights | None = None
    score_breakdown: list[ScoreCategory] = []
    strengths: list[StrengthInsight] = []
    weaknesses: list[WeaknessInsight] = []
    highest_impact_improvement: ImprovementInsight | None = None
    question_analyses: list[QuestionAnalysis] = []
    answer_pattern: AnswerPattern | None = None
    performance_timeline: list[QuestionScore] = []
    seven_day_plan: list[DailyImprovementPlan] = []
    readiness_radar: list[RadarAxis] = []
    github_project_insights: GitHubProjectInsights | None = None

    class Config:
        from_attributes = True

    @classmethod
    def from_orm_with_full_report(cls, report: Any) -> "ReportResponse":
        """
        Build a ReportResponse from a Report ORM object.

        If full_report is populated, parse the rich sections from it.
        Otherwise fall back to the scalar fields only.
        """
        fr: dict = report.full_report or {}

        def _parse_list(key: str, model: type) -> list:
            raw = fr.get(key, [])
            if not isinstance(raw, list):
                return []
            out = []
            for item in raw:
                try:
                    out.append(model(**item) if isinstance(item, dict) else item)
                except Exception:
                    pass
            return out

        def _parse_obj(key: str, model: type) -> Any:
            raw = fr.get(key)
            if not raw or not isinstance(raw, dict):
                return None
            try:
                return model(**raw)
            except Exception:
                return None

        # Strengths/weaknesses may be list[str] (old) or list[dict] (new)
        raw_strengths = fr.get("strengths", report.strengths or [])
        rich_strengths = (
            _parse_list("strengths", StrengthInsight)
            if raw_strengths and isinstance(raw_strengths[0], dict)
            else []
        ) if raw_strengths else []

        raw_weaknesses = fr.get("weaknesses", report.weaknesses or [])
        rich_weaknesses = (
            _parse_list("weaknesses", WeaknessInsight)
            if raw_weaknesses and isinstance(raw_weaknesses[0], dict)
            else []
        ) if raw_weaknesses else []

        return cls(
            id=str(report.id),
            session_id=str(report.session_id),
            created_at=report.created_at,
            overall_score=report.overall_score,
            technical_score=report.technical_score,
            behavioral_score=report.behavioral_score,
            communication_score=report.communication_score,
            hiring_recommendation=report.hiring_recommendation,
            summary=report.summary,
            strengths_flat=report.strengths if isinstance(report.strengths, list) else [],
            weaknesses_flat=report.weaknesses if isinstance(report.weaknesses, list) else [],
            learning_plan=report.learning_plan if isinstance(report.learning_plan, list) else [],
            # Rich fields from full_report
            performance_level=fr.get("performance_level", ""),
            executive_summary=fr.get("executive_summary", report.summary),
            readiness_score=fr.get("readiness_score", report.overall_score),
            readiness_level=fr.get("readiness_level", ""),
            readiness_explanation=fr.get("readiness_explanation", ""),
            performance_insights=_parse_obj("performance_insights", PerformanceInsights),
            score_breakdown=_parse_list("score_breakdown", ScoreCategory),
            strengths=rich_strengths,
            weaknesses=rich_weaknesses,
            highest_impact_improvement=_parse_obj("highest_impact_improvement", ImprovementInsight),
            question_analyses=_parse_list("question_analyses", QuestionAnalysis),
            answer_pattern=_parse_obj("answer_pattern", AnswerPattern),
            performance_timeline=_parse_list("performance_timeline", QuestionScore),
            seven_day_plan=_parse_list("seven_day_plan", DailyImprovementPlan),
            readiness_radar=_parse_list("readiness_radar", RadarAxis),
            github_project_insights=_parse_obj("github_project_insights", GitHubProjectInsights),
        )
